from django.urls import path
from .views_admin import (
    AdminLoginView, AdminMeView, AdminLogoutView,
    AdminDashboardView,
    AdminUsersView, AdminUserDetailView,
    AdminKnowledgeListCreateView, AdminKnowledgeDetailView, AdminKnowledgeRefreshView,
    AdminJobsView, AdminJobDetailView,
    AdminHistoryView,
    AdminActivityView,
    AdminSettingsView,
)

urlpatterns = [
    path("admin/login", AdminLoginView.as_view(), name="admin-login"),
    path("admin/login/", AdminLoginView.as_view()),
    path("admin/me", AdminMeView.as_view(), name="admin-me"),
    path("admin/me/", AdminMeView.as_view()),
    path("admin/logout", AdminLogoutView.as_view(), name="admin-logout"),
    path("admin/logout/", AdminLogoutView.as_view()),
    path("admin/dashboard", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/dashboard/", AdminDashboardView.as_view()),
    path("admin/users", AdminUsersView.as_view(), name="admin-users"),
    path("admin/users/", AdminUsersView.as_view()),
    path("admin/users/<uuid:user_id>", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/users/<uuid:user_id>/", AdminUserDetailView.as_view()),
    path("admin/knowledge", AdminKnowledgeListCreateView.as_view(), name="admin-knowledge-list"),
    path("admin/knowledge/", AdminKnowledgeListCreateView.as_view()),
    path("admin/knowledge/<uuid:source_id>", AdminKnowledgeDetailView.as_view(), name="admin-knowledge-detail"),
    path("admin/knowledge/<uuid:source_id>/", AdminKnowledgeDetailView.as_view()),
    path("admin/knowledge/<uuid:source_id>/refresh", AdminKnowledgeRefreshView.as_view(), name="admin-knowledge-refresh"),
    path("admin/knowledge/<uuid:source_id>/refresh/", AdminKnowledgeRefreshView.as_view()),
    path("admin/jobs", AdminJobsView.as_view(), name="admin-jobs"),
    path("admin/jobs/", AdminJobsView.as_view()),
    path("admin/jobs/<uuid:job_id>", AdminJobDetailView.as_view(), name="admin-job-detail"),
    path("admin/jobs/<uuid:job_id>/", AdminJobDetailView.as_view()),
    path("admin/history", AdminHistoryView.as_view(), name="admin-history"),
    path("admin/history/", AdminHistoryView.as_view()),
    path("admin/activity", AdminActivityView.as_view(), name="admin-activity"),
    path("admin/activity/", AdminActivityView.as_view()),
    path("admin/settings", AdminSettingsView.as_view(), name="admin-settings"),
    path("admin/settings/", AdminSettingsView.as_view()),
]
