# Generated by Django 4.2.21 on 2026-08-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(db_index=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'admin_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=150)),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'admin_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['source', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('cleaned_content', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('crawling', 'Crawling'), ('processing', 'Processing'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('updating', 'Updating')], default='queued', max_length=20)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('crawl_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.CharField(blank=True, max_length=2000)),
                ('job_type', models.CharField(choices=[('crawl', 'Crawl'), ('refresh', 'Refresh'), ('manual', 'Manual'), ('auto_update', 'Auto Update'), ('delete', 'Delete')], default='crawl', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('pages_total', models.PositiveIntegerField(default=0)),
                ('chunks_added', models.PositiveIntegerField(default=0)),
                ('chunks_updated', models.PositiveIntegerField(default=0)),
                ('chunks_removed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'knowledge_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(choices=[('url', 'Website URL'), ('text', 'Text'), ('markdown', 'Markdown'), ('pdf', 'PDF'), ('manual', 'Manual')], default='url', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('crawling', 'Crawling'), ('processing', 'Processing'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('updating', 'Updating')], db_index=True, default='queued', max_length=20)),
                ('pages_total', models.PositiveIntegerField(default=0)),
                ('pages_indexed', models.PositiveIntegerField(default=0)),
                ('failed_pages', models.PositiveIntegerField(default=0)),
                ('chunks_total', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('crawl_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_update', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('every_3_days', 'Every 3 days'), ('weekly', 'Weekly')], default='manual', max_length=20)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('max_pages', models.PositiveSmallIntegerField(default=50)),
                ('max_depth', models.PositiveSmallIntegerField(default=2)),
                ('category', models.CharField(blank=True, default='general', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'knowledge_sources',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('chunks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['status', 'is_active'], name='knowledge_s_status_15ee63_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['domain'], name='knowledge_s_domain_09d77c_idx'),
        ),
        migrations.AddField(
            model_name='knowledgejob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='knowledge.knowledgesource'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['action', 'created_at'], name='admin_activ_action_5997d7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgejob',
            index=models.Index(fields=['status', 'created_at'], name='knowledge_j_status_7fc17e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgejob',
            index=models.Index(fields=['source'], name='knowledge_j_source__82a583_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'status'], name='knowledge_d_source__9261c6_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['content_hash'], name='knowledge_d_content_c5b89e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source', 'chunk_index'], name='knowledge_c_source__7ee7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['content_hash'], name='knowledge_c_content_5d0ed0_idx'),
        ),
    ]
